apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    app: "jenkins"
    spotinst.io/restrict-scale-down: "true"
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: "sysbox-runc"
  containers:
    - name: "builder"
      imagePullPolicy: "Always"
      image: "gcr.io/hdp-gcp-316600/puppet/hdp-build-image:latest"
      resources:
        requests:
          memory: "2G"
          cpu: "1"
        limits:
          memory: "2G"
          cpu: "1"
      command:
        - "dockerd"
  tolerations:
    - key: "runOn"
      operator: "Equal"
      value: "sysbox"
      effect: "NoSchedule"
